all: house-0.png house-1.png house-2.png house-3.png house-4.png
all: house-5.png house-6.png house-7.png house-8.png house-9.png 
all: house-10.png house-11.png house-12.png

%.png: %.fig
	fig2dev -Lpng $< $@
